### ISSUE TITLE
Validate Classes

### ISSUE THREAD

**Issue by stevenpi** [dfensgmbh/biz.dfch.CS.CoffeeTracker#10]
The classes and models need validation. Use the code contracts to provide a save validation.

* [x] Controllers
  * [x] CoffeeOrdersController
  * [x] CoffeesController
  * [x] UsersController
* [ ] Logging
  * [ ] ControllerLogging
  * [ ] Logging
* [ ] Model
  * [ ] BaseEntity
  * [ ] Coffee
  * [ ] CoffeeOrder
  * [ ] User

**Comment by rufer7** [comment]
@stevenpi what's the status here?

**Comment by stevenpi** [comment]
Validating will be implemented continual
