### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by stevenpi** [dfensgmbh/biz.dfch.CS.CoffeeTracker#11]
Write integration tests with the help of [Pester](https://github.com/pester/Pester) and PowerShell

* [ ] Controller
  * [ ] CoffeeOrders
  * [ ] Coffees
  * [ ] Users

**Comment by rufer7** [comment]
@stevenpi what's about this issue? Seems to be a duplicate of #14 and #16. Correct? If yes, I suggest to create a new Issue `Pester Tests for CoffeeOrders` and then close this issue here.

**Comment by stevenpi** [comment]
duplicated by #14, #16, #20
