### ISSUE TITLE
Coffee Get Single EntityValue strange return

### ISSUE THREAD

**Issue by stevenpi** [dfensgmbh/biz.dfch.CS.CoffeeTracker#24]
when a get-request was sent and an entity was found (after the entity was updated via PUT), the api returns in a stange format. Before the entity, the api packs everything in a "d" so you must access "d" before you can access the values in powershell for example.

returned API value:
![image](https://cloud.githubusercontent.com/assets/16802792/23846874/e6c1135c-07cf-11e7-98b8-1fc89bd45b7d.png)

* [ ] fix bug
* [ ] adjust pester tests

**Comment by rufer7** [comment]
@stevenpi do you have an example? If yes, it would make sense to paste it to the issue description

**Comment by stevenpi** [comment]
instead of return SingleResult() use Ok()

**Comment by stevenpi** [comment]
resolved by c85250fd67cefeeb214d93f0831aef137061e6c3
